[tools]
bat = "latest"
btop = "latest"
bun = "latest"
delta = "latest"
fd = "latest"
fzf = "latest"
github-cli = "latest"
"github:peteretelej/tree" = "latest"
"github:tealdeer-rs/tealdeer" = { version = "latest", bin = "tldr" }
jd = "latest"
jq = "latest"
lazygit = "latest"
node = "lts"
opencode = "latest"
pnpm = "latest"
ripgrep = "latest"
usage = "latest"
uv = "latest"
yq = "latest"
zoxide = "latest"

[settings]
idiomatic_version_file_enable_tools = ["node"]
